### ISSUE TITLE
RC1 support

### ISSUE THREAD

**Issue by senj** [olohmann/Lohmann.HALight#1]
Will you have the time to make an update to RC1 in the near future?

I have problems with
options.InputFormatters.Add(new HalInputFormatter());

1) It claims that HalInputFormatter isn't an IInputFormatter and that I should add the Assembly Microsoft.AspNet.Mvc.Formatters.Json, but that has no effect.
2) On runtime, there is this expcetion: Additional information: Method not found: 'Void Microsoft.AspNet.Mvc.Formatters.JsonInputFormatter..ctor(Newtonsoft.Json.JsonSerializerSettings)'

**Comment by senj** [comment]
Sorry but this didn't solve the second error. Any hints?

**Comment by olohmann** [comment]
Sorry, @senj, I am currently totally blocked by other projects.I will look into it next week. Let me see if I can figure out the issue.

**Comment by olohmann** [comment]
I've added a sample to the repo and updated the package to 0.1.4-rc1. Please give it another try.
