### ISSUE TITLE
Not doing camelCase for nested objects

### ISSUE THREAD

**Issue by jayeshu** [olohmann/Lohmann.HALight#2]
For nested objects, the ResourceConverter is not doing camelcase.
Even after setting halOutput.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver(); it doesn't respect that.

The issue is that 
node.Add(ToCamelCase(nonResourceProperty.Name), JToken.FromObject(value));
It needs to change to ...
node.Add(ToCamelCase(nonResourceProperty.Name), JToken.FromObject(value, serializer));

**Comment by olohmann** [comment]
Thanks a lot @jayeshu! Merged. I've released an updated NuGet package for RC2 that contains your changes. Not planning on back porting that to RC1.
